database:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'TheCrims'
  username: 'root'
  password: ''
  table: 'thecrims_users'

# A few settings to improve the game performance.
settings:

  # Kick the joined player if the arena is not ready to use.
  # Permission to bypass: thecrims.setup
  kick-when-arena-not-ready: true

  # Kick the joined player if his data is not loaded correctly.
  kick-when-player-not-loaded-correctly: true